#!/usr/bin/env node

/**
 * Generate ESM (.mjs) wrappers for packages
 * This script creates ES module wrappers that import the CommonJS build
 * and dynamically re-export all discovered exports
 */

const fs = require('fs');
const path = require('path');

// Determine which package we're building
const cwd = process.cwd();
const packageName = path.basename(cwd);
const distDir = path.join(cwd, 'dist');

console.log(`Generating ESM wrapper for ${packageName}...`);

// Read the CJS index to understand exports
const indexJsPath = path.join(distDir, 'index.js');
if (!fs.existsSync(indexJsPath)) {
  console.error('Error: dist/index.js not found. Run TypeScript build first.');
  process.exit(1);
}

// Load the CommonJS module to discover exports
const cjsModule = require(indexJsPath);

// Get all named exports (excluding default)
const namedExports = Object.keys(cjsModule).filter(key => key !== 'default');

console.log(`Found ${namedExports.length} named exports:`, namedExports.slice(0, 5).join(', ') + (namedExports.length > 5 ? '...' : ''));

// Create ESM wrapper for index.mjs with dynamic exports
const esmWrapperContent = `// ESM wrapper for ${packageName}
// This file is auto-generated by generate-esm.js
import { createRequire } from 'module';

// Import the CommonJS module
const cjs = createRequire(import.meta.url)('./index.js');

// Re-export all named exports
${namedExports.map(name => `export const ${name} = cjs.${name};`).join('\n')}

// Re-export default
export default cjs.default || cjs;
`;

const indexMjsPath = path.join(distDir, 'index.mjs');
fs.writeFileSync(indexMjsPath, esmWrapperContent, 'utf8');

console.log(`✓ Created ${indexMjsPath}`);

// Create ESM wrapper for bindings.mjs
const bindingsJsPath = path.join(distDir, 'bindings.js');
if (fs.existsSync(bindingsJsPath)) {
  const bindingsCjsModule = require(bindingsJsPath);
  const bindingsNamedExports = Object.keys(bindingsCjsModule).filter(key => key !== 'default');
  
  console.log(`Found ${bindingsNamedExports.length} bindings exports`);

  const bindingsEsmContent = `// ESM wrapper for bindings
// This file is auto-generated by generate-esm.js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

// Import the CommonJS module
const cjs = require('./bindings.js');

// Re-export all named exports
${bindingsNamedExports.map(name => `export const ${name} = cjs.${name};`).join('\n')}

// Re-export default
export default cjs.default || cjs;
`;

  const bindingsMjsPath = path.join(distDir, 'bindings.mjs');
  fs.writeFileSync(bindingsMjsPath, bindingsEsmContent, 'utf8');

  console.log(`✓ Created ${bindingsMjsPath}`);
}

console.log(`\n✓ ESM wrappers generated successfully for ${packageName}!`);
console.log('\nUsage:');
console.log(`  CommonJS: const { ${namedExports[0] || 'Export'} } = require("@jamiephan/${packageName}");`);
console.log(`  ES Module: import { ${namedExports[0] || 'Export'} } from "@jamiephan/${packageName}";`);
