name: PR Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-pr:
    name: Test ${{ matrix.package }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm]
        package: [casclib, stormlib]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.4

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Run Test
        run: pnpm --filter @jamiephan/${{ matrix.package }} test:coverage
